// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_d6ddhZ7tIVCwXPgtYtzXpc9c7FUn2dA',
    appId: '1:122849701062:web:ff6fb0ace866a647a5bbc7',
    messagingSenderId: '122849701062',
    projectId: 'chat-app-b8930',
    authDomain: 'chat-app-b8930.firebaseapp.com',
    storageBucket: 'chat-app-b8930.appspot.com',
    measurementId: 'G-3STLGT8V2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-hci71bPg-37hPQJFJvivBQ8YhmzKVk',
    appId: '1:122849701062:android:9e102949b3a71368a5bbc7',
    messagingSenderId: '122849701062',
    projectId: 'chat-app-b8930',
    storageBucket: 'chat-app-b8930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkIVKl9FH7-VXm1COLhZ--9g_ME3zrNDg',
    appId: '1:122849701062:ios:0d476583f0035d6aa5bbc7',
    messagingSenderId: '122849701062',
    projectId: 'chat-app-b8930',
    storageBucket: 'chat-app-b8930.appspot.com',
    iosClientId:
        '122849701062-57k6m2mmroht2kk1j5tej34aqrvtb44j.apps.googleusercontent.com',
    iosBundleId: 'com.nyx.chat-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkIVKl9FH7-VXm1COLhZ--9g_ME3zrNDg',
    appId: '1:122849701062:ios:5567d15c54ced3aca5bbc7',
    messagingSenderId: '122849701062',
    projectId: 'chat-app-b8930',
    storageBucket: 'chat-app-b8930.appspot.com',
    iosClientId:
        '122849701062-v50fqlvcl51isiv9opr0a2lpq526o60t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
